blog/api/urls.py
from django.urls import path

from blog.api.api_views import (
    PostListCreateAPIView,
    CategoryListCreateAPIView,
    PostDetailAPIView,
    CategoryDetailAPIView
)

urlpatterns = [
    path('blogs/', PostListCreateAPIView.as_view(),
         name="blogs_list"),
    path('blogs/<str:id>', PostDetailAPIView.as_view(),
         name="blog_detail"),
    path('categories/', CategoryListCreateAPIView.as_view(),
         name="categories"),
    path('categories/<str:id>', CategoryDetailAPIView.as_view(),
         name="categories_detail"),

]

blog/urls.py
from django.urls import path
from users.views import register

from blog import views

urlpatterns = [
    path('', views.posts_list, name='posts_list_url'),
    path('user_contact/', views.user_contact, name='send_mail'),

    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', register, name="register"),

    path('post/create/', views.post_create,
         name="post_create_url"),
    path('post/<str:slug>/', views.PostDetailView.as_view(),
         name="post_detail_url"),
    path('post/<str:slug>/update/', views.PostUpdateView.as_view(),
         name="post_update_url"),
    path('post/<str:slug>/delete/', views.PostDeleteView.as_view(),
         name="post_delete_url"),

    path('post/<int:pk>/like', views.AddLike.as_view(),
         name="like"),
    path('post/<int:pk>/dislike', views.AddDisLike.as_view(),
         name="dislike"),

    path('tags/', views.tags_list, name="tags_list_url"),
    path('tag/<str:slug>/', views.TagDetailView.as_view(),
         name="tag_detail_url"),



]

blogengine/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

from rest_framework.routers import SimpleRouter

from users import views as user_views
from users.views import ViewProfile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('blog.api.urls')),
    path('chat/', include("chat.urls")),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('profile/<int:pk>/', ViewProfile.as_view(), name="profile-detail"),
    path('profile/settings/', user_views.profile, name='profile_settings'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.urls import path

from comments.views import CommentCreateView

app_name = 'comments'

urlpatterns = [
    path('create/<str:content_type>/<int:object_id>/', CommentCreateView.as_view(), name='comment-create')
]

blog/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=150, db_index=True, verbose_name="Имя категории")
    slug = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ['id']


class Post(models.Model):
    author = models.ForeignKey(User, verbose_name="Автор", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="blogs", blank=True)
    title = models.CharField(max_length=150, db_index=True, verbose_name="Заголовок")
    slug = models.SlugField(unique=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    body = models.TextField(blank=True, db_index=True, verbose_name="Контент блога")
    photo = models.ImageField(upload_to="photos/", blank=True, verbose_name="Изображение")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    replace_at = models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")
    is_published = models.BooleanField(default=True, verbose_name="Общий доступ")
    comments = GenericRelation('comments.Comment')
    likes = models.ManyToManyField(User, blank=True, related_name="likes")
    dislikes = models.ManyToManyField(User, blank=True, related_name="dislikes")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ['-created_at']


class Tag(models.Model):

    title = models.CharField(max_length=50, verbose_name="Тэг")
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tag_detail_url', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"

blog/forms.py
from django.forms import (ModelMultipleChoiceField, ModelForm, TextInput,
                          Textarea, CharField, PasswordInput, EmailField,
                          EmailInput, Form, SelectMultiple)
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

from captcha.fields import CaptchaField

from blog.models import Post, Tag


class ContactForm(Form):
    subject = CharField(
        label='Тема',
        widget=TextInput(attrs={'class': 'form-control'})
    )
    message = CharField(
        label='Текст',
        widget=Textarea(attrs={'class': 'form-control', 'rows': 5})
    )
    captcha = CaptchaField()


class PostForm(ModelForm):
    tags = ModelMultipleChoiceField(
        widget=SelectMultiple(attrs={'size': 4}),
        queryset=Tag.objects.all()
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = "Категория не выбрана"

    class Meta:
        model = Post
        fields = ["category", "title", "tags", "body", "photo", "is_published"]

        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control mb-4',
                'placeholder': 'Название статьи',
            }),
            'body': Textarea(attrs={
                'class': 'form-control mb-4',
                'placeholder': 'Контент блога',
            }),
        }

    def clean_title(self):
        title = self.cleaned_data['title']

        if len(title) > 200:
            raise ValidationError("The length mustn't exceed 200 characters")
        return title

    def clean_slug(self):
        self.slug = slugify(self.name)
        new_slug = self.cleaned_data['slug'].lower()

        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create" ')
        return new_slug


class UserLoginForm(AuthenticationForm):
    username = CharField(label='Имя пользователя',
                         widget=TextInput(attrs={
                             'class': 'form-control',
                         }))
    password = CharField(label='Пароль',
                         widget=PasswordInput(attrs={
                              'class': 'form-control'
                          }))


class UserRegisterForm(UserCreationForm):
    username = CharField(label='Имя пользователя',
                         help_text="- Имя пользователя не должен превышать 150 символов",
                         widget=TextInput(attrs={
                             'class': 'form-control',
                         }))
    password1 = CharField(label='Пароль',
                          help_text="- Длина пароля должна быть не меньше 8 символов",
                          widget=PasswordInput(attrs={
                              'class': 'form-control'
                          }))
    password2 = CharField(label='Подтверждение пароля',
                          widget=PasswordInput(attrs={
                              'class': 'form-control'
                          }))
    email = EmailField(label='E-mail',
                       widget=EmailInput(attrs={
                           'class': 'form-control'
                       }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

blog/views.py
from django.views.generic import DetailView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.db.models import Q

from blog.forms import *
from comments.forms import CommentForm


def user_contact(request):
    if request.method == 'POST':
        form = ContactForm(data=request.POST)
        if form.is_valid():
            mail = send_mail(form.cleaned_data['subject'],
                             form.cleaned_data['message'],
                             'admin@gmail.com',
                             ['admin@mail.ru'],
                             fail_silently=False
                             )
            if mail:
                messages.success(request, "Письмо успешно отправлено!")
                return redirect('posts_list_url')
            else:
                messages.error(request, "Ошибка при отправке письма!")
        else:
            messages.error(request, "Ошибка при отправке письма!")
    else:
        form = ContactForm()
    return render(request, "blog/user_contact.html", {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('posts_list_url')
    else:
        form = UserLoginForm()
    return render(request, 'blog/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('login')


def posts_list(request):
    search_query = request.GET.get('search', '')

    if search_query:
        posts = Post.objects.filter(
            Q(title__icontains=search_query) | Q(body__icontains=search_query))
    else:
        posts = Post.objects.all()

    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url
    }

    return render(request, 'blog/blog.html', context=context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            instance.tags.set(form.cleaned_data.get('tags'))
            return redirect('posts_list_url')
    else:
        form = PostForm()
    return render(request, 'blog/post_create.html', {'form': form})


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm(self.request.POST or None)
        return context


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_update.html'

    form_class = PostForm


class PostDeleteView(DeleteView):
    model = Post
    success_url = '/blog/'
    template_name = 'blog/post_delete.html'


class AddLike(DetailView):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)
        if is_like:
            post.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class AddDisLike(DetailView):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)
        if is_dislike:
            post.dislikes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class TagDetailView(DetailView):
    model = Tag
    template_name = 'blog/tag_detail.html'
    context_object_name = 'point'


def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'blog/tags_list.html', context={'tags': tags})

blog/templates/blog/blog.html
{% extends 'blog/layout.html' %}

{% block title %} Блоги Сайта {% endblock %}

{% block content %}
<h1 class="mb-5" style="color: rgba(255, 255, 255, 0.5); font-size:34px; text-align:center;">All Blogs on our Site:</h1>
{% for post in page_object.object_list %}
{% include 'blog/includes/post_card_template.html' %}
{% endfor %}

{% if is_paginated %}
<div class="test">
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item {% if not prev_url %} disabled {% endif %}">
            <a class="page-link" href="{{ prev_url }}">Previous</a>
        </li>
        {% for n in page_object.paginator.page_range %}
        {% if page_object.number == n %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only"></span></a>
        </li>
        {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not next_url %} disabled {% endif %}">
            <a class="page-link" href="{{ next_url }}">Next </a>
        </li>
    </ul>
</nav>

{% endif %}
    <div class="footer" style="text-align:center; margin: 30px 0px;">
     <small style="color:grey;" class="copyright">Copyright &copy 2021 Blackout Social Media. All Rights Reserved.</small><br>
     <small style="color:grey;" class="copyright">Property Tyler Blackout</small>
   </div>
    
{% endblock %}

blog/templates/blog/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/c37fff9f24.js" crossorigin="anonymous"></script>

    <title>{% block title %} {% endblock %}</title>

</head>
<body style="background: #101518; color: rgba(255, 255, 255, 0.5);">
 <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background: #03081A; box-shadow: 0px 4px 4px rgba(250, 20, 20, 0.25);">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'posts_list_url' %}">SecDet Samurai</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'posts_list_url' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'send_mail'%}">DevOPS</a>
              <a class="nav-item nav-link" href="{% url 'tags_list_url'%}">Tags</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'post_create_url' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'profile-detail' user.id %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
           <form class="d-flex" action="{% url 'posts_list_url' %}">
                 <input class="form-control me-2 ml-4" type="search" placeholder="Search" aria-label="Search" name="search" style="margin-right:15px;">
                 <button class="btn btn-outline-success" type="submit">Search</button>
           </form>
      </nav>
 </header>
 <main role="main" class="container">
     <div class="row">
         <div class="col-md-9">
             {% if messages %}
             {% for message in messages %}
             <div class="alert alert-{{ message.tags }}">
                 {{ message }}
             </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
      </div>
 </main>
</body>
</html>

blog/templates/blog/login.html
{% extends "blog/layout.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section" style="color: #000;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a href="#">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/post_create.html
{% extends 'blog/layout.html' %}

{% block title %} Добавление Блога {% endblock %}

{% block content %}
    <div class="features">
        <h1>Форма для добавления блога</h1>
        <form action="{% url 'post_create_url' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

                {% if field.errors %}
                <div class="alert alert-danger">
                    {{ field.errors }}
                </div>
                {% endif %}

                {% for f in form %}
                <div class="form-group">
                    <p>{{f.label}}: </p>{{ f }}
                    <div class="form-error">{{ f.errors }}</div>
                </div>
                {% endfor %}
            <button class="btn btn-success" type="submit">Добавить статью</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/layout.html' %}

{% block title %} Удаление Блога {% endblock %}

{% block content %}
    <div class="features">
        <form action="{% url 'post_delete_url' slug=post.slug %}" method="post" >
            {% csrf_token %}
            <h1>Are you sure you want to delete <b>"{{ post.title|title }}"</b> post ?</h1>
            <a href="{% url 'posts_list_url' %}">Cancel</a>
            <button type="submit" name="button" class="btn btn-danger">Удалить :(</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ post_detail_view.title }}
{% endblock %}

{% block content %}
    <h1 class="mt-3" style="color: rgba(245, 192, 51, 0.79);">{{ post.title }}</h1>
    <hr>
    {% if post.photo %}
        <p><img class="card-img-top height" src="{{ post.photo.url }}"></p>
    {% endif %}
    <hr>
    <p>{{ post.body }}</p>
      <p>{{ post.content|safe }}</p>
    <hr>

    <div class="d-flex flex-row">
        {% if request.user.is_authenticated %}
        <form action="{% url 'like' post.pk %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <button style="background-color: transparent; border:none; box-shadow:none;" type="submit">
                <i class="far fa-thumbs-up"> <span>{{ post.likes.all.count }}</span></i>
            </button>
        </form>
        {% else %}
        <div class="test" style="align-items:center;">
            <i class="far fa-thumbs-up" style="margin-right:10px;"> <span>{{ post.likes.all.count }}</span></i>
        </div>
        {% endif %}

        {% if request.user.is_authenticated %}
        <form action="{% url 'dislike' post.pk %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <button style="background-color: transparent; border:none; box-shadow:none;" type="submit">
                <i class="far fa-thumbs-down"> <span>{{ post.dislikes.all.count }}</span></i>
            </button>
        </form>
        {% else %}
            <div class="test">
                <i class="far fa-thumbs-down"> <span>{{ post.dislikes.all.count }}</span></i>
            </div>
        {% endif %}
    </div>

    <p><strong style="color: rgba(245, 192, 51, 0.79);">Кол-во комментов</strong>: <span class="badge rounded-pill bg-dark" style="color:#fff;">{{ post.comments.count }}</span></p>
    <div class="row">
        {% for comment in post.comments.all %}
            <div class="col-md-12 mt-3 mb-3" style="background: #03081A; box-shadow: 0px 4px 4px rgba(250, 20, 20, 0.25);">
                 <div class="article-metadata">
                        <img class="rounded-circle article-img" src="{{ comment.author.profile.image.url }}" style="padding:10px;"><br>
                    <div class="test_block_test" style="display:flex; justify-content:space-between;">
                        <a class="mr-2" href="#">{{ comment.author }}</a>
                        <small class="text-muted">Дата: {{ comment.created_at|date:"Y M | d дня" }}</small>
                    </div>
                </div>
                <p style="color: rgba(255, 255, 255, 0.5);">{{ comment.text }}</p>
            </div>
        {% endfor %}
    </div>
    <hr>
    {% if request.user.is_authenticated %}
        <form action="{% url 'comments:comment-create' content_type='post' object_id=post.id %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button class="btn btn-success" type="submit">Добавить комментарий</button>
        </form>
    {% else %}
        <p class="text-center">Оставлять комментарии могут только авторизованные пользователи</p>
    {% endif %}

{% endblock %}

blog/templates/blog/post_update.html
{% extends 'blog/layout.html' %}

{% block title %}
    Edit Post
{% endblock %}

{% block content %}
    <div class="features">
        <h1>Форма для редактирования блога</h1>
        <form method="post" action="{% url 'post_update_url' slug=post.slug %}" enctype="multipart/form-data">
            {% csrf_token %}

                {% if field.errors %}
                <div class="alert alert-danger">
                    {{ field.errors }}
                </div>
                {% endif %}

                {% for fields in form %}
                <div class="form-group">
                    <p>{{ fields.label }}: </p>{{ fields }}
                    <div class="form-error">{{ fields.errors }}</div>
                </div>
                {% endfor %}
            <button class="btn btn-success" type="submit">Обновить статью</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/tag_detail.html
{% extends 'blog/layout.html' %}

{% block title %}
    Posts with tag {{ point.title }} tag
{% endblock %}

{% block content %}
    <h1 class="mb-5">Posts with "{{ point.title|title }}" tag:</h1>

    {% if point.posts.all %}
        {% for post in point.posts.all %}
            {% include 'blog/includes/post_card_template.html' %}
        {% endfor %}
    {% else %}
        <p>Tags don't exist..</p>
    {% endif %}

{% endblock %}

blog/templates/blog/tags_list.html
{% extends 'blog/layout.html' %}

{% block title %}
    Page with all Tags
{% endblock %}

{% block content %}
    <h1 class="mb-5">Tags:</h1>

    {% for tag in tags %}
        <h3><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></h3>
    {% endfor %}
{% endblock %}

blog/templates/blog/user_contact.html
{% extends 'blog/layout.html' %}

{% block title %} Обратная связь {% endblock %}


{% block content %}

<h1>Обратная связь</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Send</button>
</form>

{% endblock %}